USE p1g7;

-- delete all tables and schema
DROP TABLE IF EXISTS FD.TEAM_PLAYS_COMPETITION;
DROP TABLE IF EXISTS FD.PLAYER_PARTICIPATES_GAME;
DROP TABLE IF EXISTS FD.GOAL;
DROP TABLE IF EXISTS FD.PLAYER_STAT;
DROP TABLE IF EXISTS FD.TEAM_STAT;
DROP TABLE IF EXISTS FD.SUBSTITUTION;
DROP TABLE IF EXISTS FD.MISSCONDUCT;
DROP TABLE IF EXISTS FD.GAME;
DROP TABLE IF EXISTS FD.REFEREE;
DROP TABLE IF EXISTS FD.PLAYER;
DROP TABLE IF EXISTS FD.TEAM;
DROP TABLE IF EXISTS FD.COACH;
DROP TABLE IF EXISTS FD.PERSON;
DROP TABLE IF EXISTS FD.STADIUM;
DROP TABLE IF EXISTS FD.COMPETITION;
DROP TABLE IF EXISTS FD.COUNTRY;
DROP TABLE IF EXISTS FD.CONTINENT;
DROP TABLE IF EXISTS FD.CARD;
DROP TABLE IF EXISTS FD.POSITION;
DROP TABLE IF EXISTS FD.FOOT;
DROP TABLE IF EXISTS FD.COMPETITION_TYPE;
DROP SCHEMA IF EXISTS FD;
