USE p1g7;

-- delete all tables and schema
DROP VIEW IF EXISTS FD.V_GOAL;
DROP VIEW IF EXISTS FD.V_MATCH;
DROP VIEW IF EXISTS FD.V_MISCONDUCT;
DROP VIEW IF EXISTS FD.V_SUBSTITUTION;
DROP VIEW IF EXISTS FD.V_PLAYER;
DROP VIEW IF EXISTS FD.V_TEAM;
DROP VIEW IF EXISTS FD.V_TEAM_IN_COMPETITION;
DROP TABLE IF EXISTS FD.TEAM_PLAYS_COMPETITION;
DROP TABLE IF EXISTS FD.PLAYER_PARTICIPATES_GAME;
DROP TABLE IF EXISTS FD.GOAL;
DROP TABLE IF EXISTS FD.PLAYER_STAT;
DROP TABLE IF EXISTS FD.TEAM_STAT;
DROP TABLE IF EXISTS FD.SUBSTITUTION;
DROP TABLE IF EXISTS FD.MISCONDUCT;
DROP TABLE IF EXISTS FD.GAME;
DROP TABLE IF EXISTS FD.REFEREE;
DROP TABLE IF EXISTS FD.PLAYER;
DROP TABLE IF EXISTS FD.TEAM;
DROP TABLE IF EXISTS FD.COACH;
DROP TABLE IF EXISTS FD.PERSON;
DROP TABLE IF EXISTS FD.STADIUM;
DROP TABLE IF EXISTS FD.COMPETITION;
DROP TABLE IF EXISTS FD.COUNTRY;
DROP TABLE IF EXISTS FD.CONTINENT;
DROP TABLE IF EXISTS FD.CARD;
DROP TABLE IF EXISTS FD.POSITION;
DROP TABLE IF EXISTS FD.FOOT;
DROP TABLE IF EXISTS FD.COMPETITION_TYPE;
DROP TYPE FD.idlist;
DROP SCHEMA IF EXISTS FD;

SELECT 'DROP PROCEDURE [' + SCHEMA_NAME(p.schema_id) + '].[' + p.NAME + '];'
FROM sys.procedures p
